version: '3'

services:
  python3:
    build: ./python3
#    command: uwsgi --socket :8001 --module project.wsgi --py-autoreload 1 --logto /tmp/app.log
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/src
      - ./src/static:/src/static
    ports:
      - 8000:8000
    expose:
      - "8001"
    environment:
      PYTHONPATH: /src
    env_file:
      - .env
#    depends_on:
#      - db

#  db:
#    build: postgresql
#    ports:
#      - ${POSTGRES_PORT}:5432
#    volumes:
#      - ./data:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
#    hostname: postgres
#    restart: always
#    user: root

#  nginx:
#    build: ./nginx
#    ports:
#      - "${NGNIX_PORT}:8000"
#    volumes:
#      - ./nginx/conf:/etc/nginx/conf.d
#      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
#      - ./src/static:/src/static
#    depends_on:
#      - python3

#  dbadmin:
#    image: dpage/pgadmin4:4
#    ports:
#      - ${PGADMIN_PORT}:8888
#    volumes:
#      - ./admin:/var/lib/pgadmin/storage
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#    hostname: pgadmin4
#    restart: always

  redis:
    build:
      context: ./redis
    ports:
    - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/redis_data
    restart: always

volumes:
  redis_data: