version: '3'

services:
  wsgi:
    build: ./python3
    command: uwsgi --socket :8001 --module project.wsgi --py-autoreload 1
    volumes:
      - ./src:/src
      - ./src/static:/src/static
    expose:
      - "8001"
    environment:
      PYTHONPATH: /src
    env_file:
      - .env

  asgi:
    build: ./python3
    command: daphne -b 0.0.0.0 -p 8002 project.asgi:application
    volumes:
      - ./src:/src
      - ./src/static:/src/static
    expose:
      - "8002"
    environment:
      PYTHONPATH: /src
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/src/static
    depends_on:
      - wsgi

  redis:
    build:
      context: ./redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/redis_data
    restart: always

volumes:
  redis_data: